#Build production frontend
#Requires dist folder to be built externally 
FROM node:lts-alpine

ENV NODE_ENV "production"
WORKDIR /app

COPY Caddyfile /etc/Caddyfile

COPY frontend/package*.json ./
RUN apk update && apk add caddy
RUN npm ci

RUN rm -rf node_modules public src .jshintrc babel.config.js package-lock.json package.json README.md vue.config.js
RUN cp -R dist/* . && rm -rf dist


EXPOSE 8080

ENTRYPOINT ["caddy", "--conf", "/etc/Caddyfile", "--log", "stdout", "--agree=false"]