#Build production frontend
#Requires dist folder to be built externally 
FROM abiosoft/caddy:1.0.0

ENV NODE_ENV "production"
WORKDIR /app

COPY Caddyfile /etc/Caddyfile

COPY frontend/package*.json ./
RUN apk add nodejs
RUN npm install
COPY frontend/dist ./


EXPOSE 8080