#Build production frontend
#Requires dist folder to be built externally 
FROM node:lts-alpine

WORKDIR /app

COPY Caddyfile /etc/Caddyfile

ENV NODE_ENV "development"

COPY frontend/package*.json ./
RUN apk update && apk add caddy
RUN npm install && npm install -g @vue/cli
RUN npm install -g @vue/cli-service @vue/cli-plugin-babel @vue/cli-plugin-eslint vue-template-compiler
COPY frontend ./frontend

WORKDIR /app/frontend
RUN npm run build
WORKDIR /app
RUN ls -liah && cp -R ./frontend/dist/* . && cd .. && rm -rf frontend

ENV NODE_ENV "production"

EXPOSE 8080

ENTRYPOINT ["caddy", "--conf", "/etc/Caddyfile", "--log", "stdout", "--agree=false"]