<template>
  <v-container fluid class="pa-0">
    <v-dialog
      v-model="trackingDialog"
      width="75%"
      class="mx-md-12 my-0 mx-0"
    >
      <div>
        <v-card>
          <v-card-title class="header">
            <span>{{$tc('Tracking')}}</span>
            <v-spacer></v-spacer>
            <v-btn text small depressed class="noHover closeButton" @click="close"><v-icon color="text">mdi-close</v-icon></v-btn>
          </v-card-title>
          <v-card-text>
            <p>
              This website uses Google Analytics, a web analytics service provided by Google Inc. ("Google").
            </p>

            <p>
              Google Analytics uses "cookies," which are text files stored on your computer that enable an analysis of your 
              use of the website. Some of the information generated by the cookie about your use of this website may be 
              transmitted to and stored on Google servers outside of Canada. You may refuse the use of cookies by selecting 
              the appropriate settings in your browser; however, please note that if you do so, you may not be able to use 
              the full functionality of this website. Furthermore, you can prevent Google’s collection and use of data 
              generated by the cookie and related to your use of the website by downloading and installing the browser 
              plug-in available at (
                <a href="http://tools.google.com/dlpage/gaoptout?hl=en">http://tools.google.com/dlpage/gaoptout?hl=en</a>).
              </p>

            <p>
              This website also specifies that Google Analytics apply IP Address Anonymization 
              <a href="https://support.google.com/analytics/answer/2763052?hl=en">https://support.google.com/analytics/answer/2763052?hl=en</a> 
              so that complete IP addresses are never stored by Google.
            </p>

            <p>
              You can learn more about Google’s Privacy Policies as they pertain to our partner use from 
              <a href="http://www.google.com/policies/privacy/partners/">http://www.google.com/policies/privacy/partners/</a>.
            </p>
          </v-card-text>
        </v-card>
      </div>
    </v-dialog>
    <footer class="footer">
      
        <v-toolbar color="primary" flat dense class="px-md-10">
        <v-container class="py-0">
        <!-- Navbar content -->
          <v-row class="h-100">
              <v-col cols=12 class="py-0 h-100">
                  <v-btn depressed text class="px-3 mx-0 v-top" id="footer-home" href="https://www.gov.bc.ca/">{{$tc('Home')}}</v-btn>
                  <v-btn depressed text class="px-3 mx-0 v-top" id="footer-about" href="https://www2.gov.bc.ca/gov/content/about-gov-bc-ca">{{$tc('About gov.bc.ca')}}</v-btn>
                  <v-btn depressed text class="px-3 mx-0 v-top" id="footer-disclaimer" href="http://gov.bc.ca/disclaimer/">{{$tc('Disclaimer')}}</v-btn>
                  <v-btn depressed text class="px-3 mx-0 v-top" id="footer-privacy" href="http://gov.bc.ca/privacy/">{{$tc('Privacy')}}</v-btn>
                  <v-btn depressed text class="px-3 mx-0 v-top" id="footer-tracking" @click="open">{{$tc('Tracking')}}</v-btn>
                  <v-btn depressed text class="px-3 mx-0 v-top" id="footer-accessibility" href="http://gov.bc.ca/webaccessibility/">{{$tc('Accessibility')}}</v-btn>
                  <v-btn depressed text class="px-3 mx-0 v-top" id="footer-copyright" href="http://gov.bc.ca/copyright">{{$tc('Copyright')}}</v-btn>
                  <v-btn depressed text class="px-3 mx-0 v-top" href="https://www2.gov.bc.ca/gov/content/home/contact-us">{{$tc('Contact Us')}}</v-btn>
                  <span class="vinfo">Version: {{showVersion}}</span>
                  <span class="vinfo">Api Version: {{apiVersion}}</span>
              </v-col>
          </v-row>
        </v-container>
        </v-toolbar>
    </footer>
  </v-container>
</template>

<script>
import { mapState } from "vuex";

export default {
  components: {

  },
  methods:{
    open() {
      this.trackingDialog = true;
      this.$gtag.event('Open', {
        'event_category': 'Modal',
        'event_label': 'Tracking'
      })
    },
    close() {
      this.trackingDialog = false;
      this.$gtag.event('Close', {
        'event_category': 'Modal',
        'event_label': 'Tracking'
      })
    }
  },
  data(){
    return {
      trackingDialog: false
    }
  },
  computed: {
    ...mapState({
            version: state => state.version.version,
            v: state => state.version.v,
            hash: state => state.version.hash,
            apiVersion: state => state.version.apiVersion,
    }),
    showVersion: function(){
      return this.v + "-" + this.hash.substring(0,7);
    }
  },
  watch: {
    $route(){
      this.$store.dispatch('version/getVersion')
    }
  }
}
</script>

<style scoped>

  .vinfo{
    font-size: 10px;
    color: var(--v-text-base);
    padding-right: 5px;
  }

</style>

<style>
    .footer {
        min-height: 45px;
        background-color: var(--v-primary-base);
        min-width: 100%;
        /* z-index: 100; */
        bottom: 0;
        position: absolute;
        border-top-color: var(--v-govYellow-base) !important;
        border-top-width: 2px !important;
        border-top-style: solid !important;
    }

    .footer a {
        color: var(--v-text-base) !important;
        text-decoration: none;
    }
    .a--active.footer:before, .a.footer:focus:before, .a.footer:hover:before {
        background: none !important;
    }
    .h-100 {
      height: 100% !important;
    }
    .v-top {
      vertical-align: top;
    }

    .header{
        background: var(--v-menu_secondary-base);
        color: var(--v-text-base);
        font-size: 16px;
        font-weight: normal;
    }
    

</style>
