apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "ckan-ui.fullname" . }}
  labels:
    app: {{ template "ckan-ui.name" . }}
    chart: {{ template "ckan-ui.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "ckan-ui.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "ckan-ui.name" . }}
        release: {{ .Release.Name }}
    spec:
      volumes:
      - name: config
        configMap:
          name: {{ template "ckan-ui.fullname" . }}-configmap
          defaultMode: 511
      - name: secrets
        secret:
          secretName: {{ template "ckan-ui.fullname" . }}-secrets
          defaultMode: 511
      containers:
        - name: {{ .Chart.Name }}-frontend
          image: "{{ .Values.image.repository.frontend }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: HOSTNAME
              value: "localhost"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository.backend }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: secrets
              mountPath: /app/config/default.json
              subPath: default.json
            - name: config
              mountPath: /app/config/prod.json
              subPath: prod.json

          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /status
              port: http
          readinessProbe:
            httpGet:
              path: /status
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
