{{ if .Values.openshiftCICD }}

apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
    name: {{ template "ckan-ui.fullname" . }}-image
    labels:
        app: {{ template "ckan-ui.name" . }}
        chart: {{ template "ckan-ui.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
spec: {}

---

apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
    name: {{ template "ckan-ui.fullname" . }}-frontend-image
    labels:
        app: {{ template "ckan-ui.name" . }}
        chart: {{ template "ckan-ui.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
spec: {}

{{- end }}