{{ if .Values.openshiftCICD }}

apiVersion: build.openshift.io/v1
kind: BuildConfig
status: 
  lastVersion: 0
metadata:
  name: {{ template "ckan-ui.fullname" . }}-image
  labels:
    app: {{ template "ckan-ui.name" . }}
    chart: {{ template "ckan-ui.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  nodeSelector: {}
  resources:
    requests:
        cpu: 2000m
        memory: 4G
    limits:
        cpu: 3000m
        memory: 8G
  output:
    to:
      kind: ImageStreamTag
      name: {{ template "ckan-ui.fullname" . }}-image:{{ .Values.repo.tag }}
  source:
    type: Git
    git:
      ref: {{ .Values.repo.ref | quote }}
      uri: {{ .Values.repo.url | quote }}
    
  strategy:
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
    - type: "imageChange"
      imageChange:
        from:
          kind: "ImageStreamTag"
          name: "{{ template "ckan-ui.fullname" . }}-frontend-image:latest"

---

apiVersion: build.openshift.io/v1
kind: BuildConfig
status: 
  lastVersion: 0
metadata:
  name: {{ template "ckan-ui.fullname" . }}-frontend-image
  labels:
    app: {{ template "ckan-ui.name" . }}
    chart: {{ template "ckan-ui.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  nodeSelector: {}
  resources:
    requests:
        cpu: 2000m
        memory: 4G
    limits:
        cpu: 3000m
        memory: 8G
  output:
    to:
      kind: ImageStreamTag
      name: {{ template "ckan-ui.fullname" . }}-frontend-image:{{ .Values.repo.tag }}
  source:
    type: Git
    git:
      ref: {{ .Values.repo.ref | quote }}
      uri: {{ .Values.repo.url | quote }}
    
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile-frontend
  successfulBuildsHistoryLimit: 5
  triggers:
    - type: "GitHub"
      github: 
        secretReference:
          name: "{{ .Release.Name }}-git-webhook-secret"

{{- end }}
