apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ckan-ui.fullname" . }}-secrets
  labels:
    app: {{ template "ckan-ui.name" . }}
    chart: {{ template "ckan-ui.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
{{ $json := printf "{\n\"oidc\": {\n\t\"clientSecret\": \"%s\"\n},\n\"sessionSecret\": \"%s\"\n}" .Values.oidc.clientSecret .Values.sessionSecret }}
data:
  default.json: {{ $json | b64enc }}