apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ckan-ui.fullname" . }}-secrets
  labels:
    app: {{ template "ckan-ui.name" . }}
    chart: {{ template "ckan-ui.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  sessionSecret: "{{ .Values.sessionSecret | b64enc}}"
  oidc:
    clientSecret: "{{ .Values.oidc.clientSecret | b64enc }}"
