name: Build Ckan UI frontend

on:
  push:
    branches: [ad-ga-build-ui]
    paths:
      - "frontend/**"
      - ".github/workflows/build-ui.yaml"
  workflow_dispatch:
    branches: [ad-ga-build-ui]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cluster Login
        uses: redhat-developer/openshift-actions@v1.1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT4_SERVER_URL }}
          parameters: '{"apitoken": "${{ secrets.OPENSHIFT4_SA_PASSWORD }}"}'
          cmd: |
            'version'

      - name: Login to Openshift Docker
        run : |
          docker login ${{ secrets.OPENSHIFT4_EXTERNAL_REPOSITORY }} -u ${{ secrets.OPENSHIFT4_SA_USERNAME }} -p ${{ secrets.OPENSHIFT4_SA_PASSWORD }}
            
      - name: Build the Docker image
        run: |          
          
          docker build -t cadi-ui-ocp4-ckan-ui-frontend-image:latest -f Dockerfile-frontend .
          
          docker tag cadi-ui-ocp4-ckan-ui-frontend-image:latest ${{ secrets.OPENSHIFT4_EXTERNAL_REPOSITORY }}/${{ secrets.OPENSHIFT4_TOOLS_NAMESPACE }}/cadi-ui-ocp4-ckan-ui-frontend-image:latest
          docker push ${{ secrets.OPENSHIFT4_EXTERNAL_REPOSITORY }}/${{ secrets.OPENSHIFT4_TOOLS_NAMESPACE }}/cadi-ui-ocp4-ckan-ui-frontend-image:latest
